# Site settings
title: Human Speed
description: >
  Human speed is about truly experiencing the world around you. Walking, sailing and cycling 
  let you see, hear, and feel a place in a way that driving never can. These slower 
  methods of travel give you time to notice details - the way light hits a tree, the 
  sounds of a neighborhood, the texture of the ocean.<br><br>
  Public transit like trains and buses can also offer a more concious way to travel, 
  letting you take in the scenery without the stress of driving. Cars, by contrast, 
  trap you in a bubble of constant attention, forcing you to focus on the road instead 
  of the world passing by. For bystanders they create noise and traffic that disconnect 
  us from our enjoyment of the environment.<br><br>
  This website shares stories of travel at a human pace, hoping to show that the journey 
  can be just as important as the destination.

short_description: >
  Human speed is about truly experiencing the world around you. Walking, sailing and cycling 
  let you see, hear, and feel a place in a way that driving never can. These slower 
  methods of travel give you time to notice details - the way light hits a tree, the 
  sounds of a neighborhood, the texture of the ocean.

url: 'https://www.human-speed.org/'

baseurl: ''

# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

disable_landing_page: true

author:
  name: 'Steve Bannister'
  email: steve.bannister@hey.com
  mastodon: milgrim@mas.to
#  github_username: milgrim2023
  instagram: bikebadger
  strava: 298004
  komoot: 4139383193904

defaults:
  -
    scope:
      path: 'posts'
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /posts/:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false


plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'vendor', 'Gemfile.lock', 'screenshot.png', 'docker-compose.yml', 'humans.txt']
